apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok-apiops-demo
  namespace: ngrok-apiops-demo
  labels:
    app: ngrok-apiops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok-apiops-demo
  template:
    metadata:
      labels:
        app: ngrok-apiops-demo
    spec:
      containers:
      - name: ngrok-apiops-demo
        image: joelhans/ngrok-apiops-demo
        ports:
          - name: http
            containerPort: 5000
